# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cv', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=10)),
                ('date_applied', models.DateField(verbose_name='Applied')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('job_area', models.CharField(max_length=12)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pub_date', models.DateTimeField(verbose_name='date job published')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
    ]
